kind: Environment
apiVersion: hyscale.io/v1
metadata:
  name: stage
  applicationName: empservice
  labels:
    type: stage
spec:
  registry: gcr
  k8sCluster: GKEQA
  k8sNamespace: stage-employee
  hosts:  #acting like lb props
    APP_DOMAIN: api.sampleapp.com
    WEB_DOMAIN: web.sampleapp.com
